language: php

php:
    - 7.1
    - 7.2
    - 7.3
    - nightly

env:
    - COMPOSER_OPTS=""
    - COMPOSER_OPTS="--prefer-lowest"

matrix:
    allow_failures:
        - php: nightly
    fast_finish: true

sudo: false
before_install: 
    - if [[ "$TRAVIS_PHP_VERSION" NOT IN ("7.3", "nightly") ]]; then pecl install mailparse ; fi
    - if [[ "$TRAVIS_PHP_VERSION" IN ("7.3", "nightly") ]]; then chmod +x ./compile_mailparse.sh ; fi
    - if [[ "$TRAVIS_PHP_VERSION" IN ("7.3", "nightly") ]]; then ./compile_mailparse.sh ; fi

before_script:
    - composer self-update
    - composer update $COMPOSER_OPTS

script:
    - mkdir -p build/logs
    - ./vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml
    - ./vendor/bin/phpcs src --standard=psr2
    - ./vendor/bin/phpcs tests --standard=psr2

after_script:
    - ./vendor/bin/coveralls -v
