language: php

php:
    - 7.1
    - 7.2
    - 7.3
    - nightly

env:
    - COMPOSER_OPTS=""
    - COMPOSER_OPTS="--prefer-lowest"

matrix:
    allow_failures:
        - php: nightly
    fast_finish: true

sudo: false

before_script:
    - if [[ "$TRAVIS_PHP_VERSION" != "7.3" ]]; then pecl install mailparse ; fi
    - if [[ "$TRAVIS_PHP_VERSION" = "7.3" ]]; then git clone https://github.com/php/pecl-mail-mailparse.git ; fi
    - if [[ "$TRAVIS_PHP_VERSION" = "7.3" ]]; then cd pecl-mail-mailparse ; fi
    - if [[ "$TRAVIS_PHP_VERSION" = "7.3" ]]; then phpize ; fi
    - if [[ "$TRAVIS_PHP_VERSION" = "7.3" ]]; then ./configure ; fi
    - if [[ "$TRAVIS_PHP_VERSION" = "7.3" ]]; then make ; fi
    - if [[ "$TRAVIS_PHP_VERSION" = "7.3" ]]; then sudo make install ; fi
    - composer self-update
    - composer update $COMPOSER_OPTS

script:
    - mkdir -p build/logs
    - ./vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml
    - ./vendor/bin/phpcs src --standard=psr2
    - ./vendor/bin/phpcs tests --standard=psr2

after_script:
    - ./vendor/bin/coveralls -v
