language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - hhvm

before_script:
    - echo "extension = mailparse.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - composer self-update
    - composer install
