language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm

before_script:
    - sh -c 'if [ $(php -r "echo (int) defined(\"HHVM_VERSION\");") -eq 0 ]; then pecl install mailparse; fi'
    - composer self-update
    - composer install

script:
    - mkdir -p build/logs
    - ./vendor/bin/phpunit -c ./ --coverage-text --coverage-clover build/logs/clover.xml
    - ./vendor/bin/phpcs src --standard=psr2
    - ./vendor/bin/phpcs test --standard=psr2

after_script:
    - ./vendor/bin/coveralls -v
