language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - hhvm

before_script:
    - pyrus install pear/mailparse
    - phpenv rehash
    - pecl install mailparse
    - composer self-update
    - composer install
