language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6

before_script:
    - pecl install mailparse
    - composer self-update
    - composer install
    - mkdir -p build/logs

script:
    - phpunit -c ./ --coverage-text --coverage-clover build/logs/clover.xml
    
after_script:
    - php vendor/bin/coveralls -v
