name: CI

on: [push, pull_request]

jobs:

  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Composer install
      run: composer update --no-progress --ignore-platform-reqs
    - name: PHPCS
      run: |
        composer require friendsofphp/php-cs-fixer  --ignore-platform-reqs
        ./vendor/bin/php-cs-fixer fix src 
        ./vendor/bin/php-cs-fixer fix tests
    - name: Auto Commit
      run: |
        git remote set-url origin https://eXorus:${{ secrets.TADA }}@github.com/php-mime-mail-parser/php-mime-mail-parser
        git config --global user.email "you@example.com"
        git config --global user.name "PHP CS Fixer"
        git checkout ${{ GITHUB_REF }}
        git add src
        git add tests
        git commit -m "PHP CS Fixer" || echo "No changes found. Nothing to commit."
        git push
        
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.1, 7.2, 7.3]
        composer: ["", "--prefer-lowest"]
    steps:
    - uses: actions/checkout@v1
    - name: Change PHP version
      run: sudo update-alternatives --set php /usr/bin/php${{ matrix.php }}
    - name: Install mailparse
      run: sudo apt install php-mailparse
    - name: Composer install
      run: composer update ${{ matrix.composer }} --no-progress
    - name: PHP Version
      run: php -v
    - name: PhpUnit
      run: |
        mkdir -p build/logs
        ./vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml -c phpunit.xml.dist --whitelist src
    - name: PHPCS
      run: |
        ./vendor/bin/phpcs src --standard=psr2
        ./vendor/bin/phpcs tests --standard=psr2
    - name: Coveralls
      env:
        COVERALLS_REPO_TOKEN: BS4E6dtQa8fUMHQiOTFbQICA6ydxSqkRt
      run: ./vendor/bin/php-coveralls -v
     
