name: CI

on: [push]

jobs:
        
  php-cs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Composer update
      run: composer update --no-progress --ignore-platform-reqs
    - name: PHP CS
      run: ./vendor/bin/phpcs src tests --standard=psr2
     
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.1, 7.2, 7.3]
        composer: ["", "--prefer-lowest"]
    steps:
    - uses: actions/checkout@v1
    - name: Change PHP version
      run: sudo update-alternatives --set php /usr/bin/php${{ matrix.php }} && php -v
    - name: Install mailparse
      run: sudo apt install php-mailparse
    - name: Composer update
      run: composer update ${{ matrix.composer }} --no-progress
    - name: PhpUnit
      run: |
        mkdir -p build/logs
        ./vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml -c phpunit.xml.dist --whitelist src
    - name: Coveralls
      env:
        COVERALLS_REPO_TOKEN: BS4E6dtQa8fUMHQiOTFbQICA6ydxSqkRt
      run: ./vendor/bin/php-coveralls -v
     
