name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install mailparse
      run: sudo apt install php-mailparse
    - name: Composer install
      run: composer install
    - name: PhpUnit
      run: ./vendor/bin/phpunit
