name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install mailparse
      run: |
        sudo apt install php-mailparse
    - name: Composer install
      run: composer install

  test:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: PhpUnit
      run: |
        ls 
        pwd
        ls ./vendor
        ls ./vendor/bin
        ./vendor/bin/phpunit
